const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Behaviors.scrollto,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Fade,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.Azerion_Integration_SDK,
		C3.Behaviors.Timer,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.System.Exps.tickcount,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Azerion_Integration_SDK.Cnds.IsAdPlaying,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.ChangeTags,
		C3.Plugins.Sprite.Exps.Tags,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Azerion_Integration_SDK.Acts.InitializeSDK,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.JavaScriptInEvents.Azerionintegrationevent_Event3_Act6,
		C3.JavaScriptInEvents.Azerionintegrationevent_Event3_Act7,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnLoadProgress,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnLoadStart,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnLoadComplete,
		C3.Plugins.Azerion_Integration_SDK.Acts.AddListeners,
		C3.JavaScriptInEvents.Azerionintegrationevent_Event8_Act1,
		C3.JavaScriptInEvents.Azerionintegrationevent_Event8_Act2,
		C3.JavaScriptInEvents.Azerionintegrationevent_Event9_Act1,
		C3.JavaScriptInEvents.Azerionintegrationevent_Event10_Act1,
		C3.Plugins.Azerion_Integration_SDK.Acts.PreloadAd,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Azerion_Integration_SDK.Acts.ShowInterstitialAd,
		C3.Plugins.Azerion_Integration_SDK.Acts.ShowRewardedAd,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnGameStart,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnGameEnd,
		C3.Plugins.Azerion_Integration_SDK.Acts.SendScoreEvent,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.JavaScriptInEvents.Azerionintegrationevent_Event27_Act2,
		C3.JavaScriptInEvents.Azerionintegrationevent_Event29_Act2,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{obj_cell: 0},
	{is_complete: 0},
	{hexa_tile: 0},
	{Touch: 0},
	{ScrollTo: 0},
	{level: 0},
	{Browser: 0},
	{Text: 0},
	{Text2: 0},
	{tags: 0},
	{Rotate: 0},
	{shine: 0},
	{juldiz: 0},
	{Anchor: 0},
	{TiledBackground: 0},
	{check: 0},
	{sol: 0},
	{on: 0},
	{Bullet: 0},
	{Sine: 0},
	{confetti: 0},
	{Audio: 0},
	{lvl_ui: 0},
	{taptocontinue: 0},
	{Tipe: 0},
	{timer_ux: 0},
	{time_ui: 0},
	{LocKey: 0},
	{hexatext: 0},
	{iks: 0},
	{taptorestart: 0},
	{jolak: 0},
	{clock: 0},
	{boostertimer: 0},
	{san_booster: 0},
	{snow: 0},
	{pause: 0},
	{play: 0},
	{zvukbar: 0},
	{dom: 0},
	{Mask: 0},
	{TiledBackground_strelka: 0},
	{touch_icon: 0},
	{info_text: 0},
	{playbutton: 0},
	{logo: 0},
	{info_text2: 0},
	{LocalStorage: 0},
	{Fade: 0},
	{TiledBackground2: 0},
	{LangCode: 0},
	{lang_text: 0},
	{English: 0},
	{tandau: 0},
	{playbutton2: 0},
	{nastroi: 0},
	{JSON_Config: 0},
	{AJAX: 0},
	{AzIntegrationPlugin: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Timer: 0},
	{loading_fill: 0},
	{buttons: 0},
	{DRAG_STATE: 0},
	{DRAG_STATE_WAITING: 0},
	{DRAG_STATE_DRAGGING: 0},
	{OBJ_DRAGGING_ID: 0},
	{TimerDefault: 0},
	{TimerSteps: 0},
	{startgame: 0},
	{freeze: 0},
	{level_: 0},
	{levelnumber: 0},
	{hexa_parent_selected: 0},
	{hexa_parent_other: 0},
	{obj_other: 0},
	{win: 0},
	{group: 0},
	{GAME_STATE: 0},
	{GAME_STATE_PLAYING: 0},
	{GAME_STATE_WIN: 0},
	{GAME_STATE_LOSE: 0},
	{GAME_STATE_NONE: 0},
	{DISTANCE_FOR_OVERLAP_HEXATILE: 0},
	{LANG: 0},
	{audio_enabled: 0},
	{rewardAvailable: 0},
	{HasPlatformAudioControls: 0},
	{HasFocusAPI: 0},
	{HasPlatformSplashScreen: 0},
	{AllAssetsLoaded: 0},
	{PREROLL_ENABLED: 0},
	{IsWatchAd: 0},
	{HasFocus: 0},
	{PlatformLanguage: 0},
	{HasPlatformLanguage: 0},
	{progress: 0},
	{lvlNr: 0},
	{cScore: 0},
	{completed: 0},
	{currentScore: 0},
	{cummulativeScore: 0},
	{levelNr: 0},
	{LoadProg: 0},
	{save_name: 0}
];

self.InstanceType = {
	obj_cell: class extends self.ISpriteInstance {},
	hexa_tile: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	level: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	tags: class extends self.ISpriteInstance {},
	shine: class extends self.ISpriteInstance {},
	juldiz: class extends self.IParticlesInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	check: class extends self.ISpriteInstance {},
	sol: class extends self.ISpriteInstance {},
	on: class extends self.ISpriteInstance {},
	confetti: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	lvl_ui: class extends self.ISpriteFontInstance {},
	taptocontinue: class extends self.ISpriteFontInstance {},
	timer_ux: class extends self.ITextInstance {},
	time_ui: class extends self.ISpriteFontInstance {},
	hexatext: class extends self.ISpriteFontInstance {},
	iks: class extends self.ISpriteInstance {},
	taptorestart: class extends self.ISpriteFontInstance {},
	jolak: class extends self.ISpriteInstance {},
	clock: class extends self.ISpriteInstance {},
	boostertimer: class extends self.ISpriteInstance {},
	san_booster: class extends self.ISpriteFontInstance {},
	snow: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	zvukbar: class extends self.ISpriteInstance {},
	dom: class extends self.ISpriteInstance {},
	Mask: class extends self.ISpriteInstance {},
	TiledBackground_strelka: class extends self.ITiledBackgroundInstance {},
	touch_icon: class extends self.ISpriteInstance {},
	info_text: class extends self.ISpriteFontInstance {},
	playbutton: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	info_text2: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	lang_text: class extends self.ISpriteFontInstance {},
	English: class extends self.ISpriteInstance {},
	tandau: class extends self.ISpriteInstance {},
	playbutton2: class extends self.ISpriteInstance {},
	nastroi: class extends self.ISpriteInstance {},
	JSON_Config: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	AzIntegrationPlugin: class extends C3.Plugins.Azerion_Integration_SDK.Instance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	loading_fill: class extends self.ITiledBackgroundInstance {},
	buttons: class extends self.ISpriteInstance {}
}